
version: '3'

services:
  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    # depends_on:
    #   - mariadb
    #   - wordpress
    restart: always
    ports:
      - "443:443"
    # volumes:
    #   - ./home/:/usr/share/nginx/html/
    networks:
      - mynetwork

#   mariadb:
#     build: ./requirements/mariadb/
#     image: mariadb
#     environment:
#       - MARIADB_ROOT_PASSWORD=1234
#       - MARIADB_DATABASE=wp_db
#       - MARIADB_USER=wp_user
#       - MARIADB_PASSWORD=1234
#     restart: always
#     expose:
#       - 3306
#     volumes:
#       - mariadb:/var/lib/mysql
#     networks:
#       - mynetwork

#   wordpress:
#     build: ./requirements/wordpress/
#     depends_on:
#       - mariadb
#     image: wordpress
#     ports:
#       - 9000
#     restart: always
#     environment:
#       - WORDPRESS_DB_HOST=mariadb:3306
#       - WORDPRESS_DB_USER=wp_user
#       - WORDPRESS_DB_PASSWORD=1234
#       - WORDPRESS_DB_NAME=wp_db
#     volumes:
#       - wp_data:/var/www/html
#     networks:
#       - mynetwork

# volumes:
#   mariadb:
#   wp_data:

networks:
  mynetwork:
    driver : bridge