
version: '3'

services:
  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    depends_on:
      - mariadb
      - wordpress
    restart: always
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html/wordpress
    networks:
      - mynetwork
  
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    env_file: 
      - .env
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - DB:/var/lib/mysql
    networks:
      - mynetwork

  wordpress:
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    image: wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/html/wordpress
    networks:
      - mynetwork
    
  site:
    build: ./requirements/bonus/web_statique/
    container_name: web_statique
    image: web_statique
    hostname: localhost
    ports:
      - "444:444"
    restart: always
  
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    image: adminer
    volumes:
      - DB:/var/lib/mysql
    restart: always
    ports:
      - 9090:9090
    networks:
      - mynetwork

  cadvisor:
    build: ./requirements/bonus/cadvisor
    container_name: cadvisor
    image: cadvisor
    networks:
      - mynetwork
    ports:
      - "6500:6500"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro 


volumes:
  DB:
    name: mariadb
    driver_opts:
      o: bind
      type: none
      device: /home/tbouzalm/data/mariadb
  wp_data:
    name: wordpress
    driver_opts:
      o: bind
      type: none
      device: /home/tbouzalm/data/wordpress

networks:
  mynetwork:
    driver : bridge
    name: mynetwork