FROM debian:buster

RUN apt-get update -y && apt-get install -y nginx

COPY tools/nginx.conf /etc/nginx/nginx.conf

COPY web/index.html /var/www/html

RUN chmod 777 /var/www/html/index.html

CMD ["nginx", "-g", "daemon off;"]